# Generated by Django 4.1.2 on 2023-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='id',
        ),
        migrations.AlterField(
            model_name='queries',
            name='query_id',
            field=models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
