# Generated by Django 4.1.2 on 2023-06-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_queries_id_alter_queries_query_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='AMR_file_path',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='queries',
            name='VFG_file_path',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='queries',
            name='mlst_file_path',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='queries',
            name='tree_file_path',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='queries',
            name='tree_visual_path',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
