# Generated by Django 4.1.2 on 2023-06-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_queries_amr_file_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='AMR_file_path',
            new_name='AMR_tsv_path',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='VFG_file_path',
            new_name='VFG_tsv_path',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='mlst_file_path',
            new_name='mlst_tsv_path',
        ),
    ]
