# Generated by Django 4.1.2 on 2023-06-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_rename_amr_file_path_queries_amr_tsv_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='AMR_fasta_path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='queries',
            name='VFG_fasta_path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='queries',
            name='mlst_json_path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
