# Generated by Django 4.1.2 on 2023-06-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_queries_amr_fasta_path_queries_vfg_fasta_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='ssu_fasta_path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='queries',
            name='ssu_gff_path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
