# Generated by Django 4.1.2 on 2023-06-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_queries_ssu_fasta_path_queries_ssu_gff_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='mlst_json_path',
        ),
        migrations.AddField(
            model_name='queries',
            name='mlst_json',
            field=models.JSONField(null=True),
        ),
    ]
