# Generated by Django 4.1.2 on 2023-02-13 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('taxid', models.IntegerField(primary_key=True, serialize=False)),
                ('specie_name', models.CharField(max_length=255)),
                ('type_strains', models.CharField(max_length=255)),
                ('lpsn_address', models.CharField(max_length=255)),
                ('risk_group', models.CharField(max_length=255)),
                ('pathogenicity', models.CharField(max_length=255)),
                ('ncbi_genus', models.CharField(max_length=255)),
                ('ncbi_complex', models.CharField(max_length=255)),
                ('ncbi_specie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('accession', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('datasource', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('source_detail', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.species')),
            ],
        ),
    ]
