# Generated by Django 4.1.2 on 2023-02-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='parent_taxid',
            field=models.IntegerField(db_index=True, default=1763),
        ),
        migrations.AlterField(
            model_name='species',
            name='specie_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxid',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='accession',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
