# Generated by Django 4.1.2 on 2023-02-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_specie_name_species_name_species_tax_level_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Strain',
            new_name='Strains',
        ),
    ]
