# Generated by Django 4.1.2 on 2023-02-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_strain_strains'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='strains_count',
            field=models.IntegerField(default=None),
        ),
    ]
