# Generated by Django 4.1.2 on 2023-02-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_species_strains_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='parent_taxid',
            field=models.CharField(db_index=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxid',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='strains',
            name='specie',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='api.species'),
        ),
    ]
