# Generated by Django 4.1.2 on 2023-03-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_species_other_type_strains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='other_type_strains',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
    ]
