# Generated by Django 4.1.2 on 2023-03-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_species_other_type_strains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strains',
            name='datasource',
        ),
    ]
