# Generated by Django 4.1.2 on 2023-03-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_ncbi_specie_species_ncbi_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strains',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
