# Generated by Django 4.1.2 on 2023-03-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_strains_source_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='strains',
            name='MLST',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='strains',
            name='source_detail',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
