# Generated by Django 4.1.2 on 2023-03-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_amr_genes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amr_genes',
            name='drug_class',
        ),
        migrations.AddField(
            model_name='amr_genes',
            name='mechanism_ontology_id',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='amr_genes',
            name='mechanism',
            field=models.CharField(choices=[('AE', 'antibiotic efflux'), ('AI', 'antibiotic inactivation'), ('ATP', 'antibiotic target protection'), ('ATA', 'antibiotic target alteration'), ('ATR', 'antibiotic target replacement'), ('RP', 'aeduced permeability to antibiotic')], default=None, max_length=10),
        ),
    ]
