# Generated by Django 4.1.2 on 2023-03-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_amr_genes_drug_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amr_genes',
            name='mechanism',
            field=models.CharField(choices=[('AE', 'antibiotic efflux'), ('AI', 'antibiotic inactivation'), ('ATP', 'antibiotic target protection'), ('ATA', 'antibiotic target alteration'), ('ATR', 'antibiotic target replacement'), ('RP', 'aeduced permeability to antibiotic')], default=None, max_length=50),
        ),
    ]
