# Generated by Django 4.1.2 on 2023-03-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_amr_genes_mechanism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amr_genes',
            name='mechanism',
            field=models.CharField(choices=[('AE', 'antibiotic efflux'), ('AI', 'antibiotic inactivation'), ('ATP', 'antibiotic target protection'), ('ATA', 'antibiotic target alteration'), ('ATR', 'antibiotic target replacement'), ('RP', 'reduced permeability to antibiotic')], default=None, max_length=50),
        ),
    ]
