# Generated by Django 4.1.2 on 2023-03-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_amr_genes_mechanism'),
    ]

    operations = [
        migrations.AddField(
            model_name='amr_genes',
            name='drug_class',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
