# Generated by Django 4.1.2 on 2023-03-15 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_amr_genes_drug_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMR_Sequences',
            fields=[
                ('amr_seqid', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('contig', models.CharField(blank=True, default=None, max_length=50)),
                ('strand', models.CharField(blank=True, choices=[('+', 'positive'), ('-', 'negative')], default=None, max_length=10)),
                ('position', models.CharField(blank=True, default=None, max_length=20)),
                ('coverage', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('identity', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('ref_strain', models.CharField(blank=True, default=None, max_length=50)),
                ('card_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='api.amr_genes')),
                ('strain_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='api.strains')),
            ],
        ),
    ]
