# Generated by Django 4.1.2 on 2023-03-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_amr_sequences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amr_sequences',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='amr_sequences',
            old_name='strain_id',
            new_name='strain',
        ),
        migrations.AddField(
            model_name='amr_sequences',
            name='gene_name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
