# Generated by Django 4.1.2 on 2023-03-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_card_id_amr_sequences_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amr_sequences',
            name='coverage',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='amr_sequences',
            name='identity',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
    ]
