# Generated by Django 4.1.2 on 2023-03-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_amr_sequences_coverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amr_sequences',
            name='card',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='api.amr_genes'),
        ),
        migrations.AlterField(
            model_name='amr_sequences',
            name='strain',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='api.strains'),
        ),
    ]
