# Generated by Django 4.1.2 on 2023-03-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_amr_sequences_card_alter_amr_sequences_strain'),
    ]

    operations = [
        migrations.CreateModel(
            name='VF_Genes',
            fields=[
                ('vfg_id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('gene_name', models.CharField(blank=True, default=None, max_length=50)),
                ('genbank_id', models.CharField(blank=True, default=None, max_length=15)),
                ('vf_id', models.CharField(blank=True, default=None, max_length=10)),
                ('vf_name', models.CharField(blank=True, default=None, max_length=50)),
                ('vf_full_name', models.CharField(blank=True, default=None, max_length=50)),
                ('vfc_id', models.CharField(blank=True, default=None, max_length=10)),
                ('vfc_name', models.CharField(blank=True, default=None, max_length=50)),
                ('source_organism', models.CharField(blank=True, default=None, max_length=50)),
                ('source_strain', models.CharField(blank=True, default=None, max_length=50)),
                ('count_by_strains', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
    ]
