# Generated by Django 4.1.2 on 2023-03-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_vf_genes_source_strain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VF_Sequences',
            fields=[
                ('vf_seqid', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('contig_name', models.CharField(blank=True, default=None, max_length=50)),
                ('strand', models.CharField(blank=True, default=None, max_length=50)),
                ('position', models.CharField(blank=True, default=None, max_length=50)),
                ('coverage', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('identity', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('strain_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='api.strains')),
                ('vfg_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='api.vf_genes')),
            ],
        ),
    ]
