# Generated by Django 4.1.2 on 2023-03-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_vf_genes_count_by_strains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vf_sequences',
            old_name='strain_id',
            new_name='strain',
        ),
        migrations.RenameField(
            model_name='vf_sequences',
            old_name='vfg_id',
            new_name='vfg',
        ),
    ]
