# Generated by Django 4.1.2 on 2023-03-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_strain_id_vf_sequences_strain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strains',
            name='ncbi_complex',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='strains',
            name='ncbi_genus',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='strains',
            name='ncbi_species',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='strains',
            name='species_name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
