# Generated by Django 4.1.2 on 2023-03-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_strains_ncbi_complex_strains_ncbi_genus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strains',
            name='vf_summary',
            field=models.JSONField(null=True),
        ),
    ]
