# Generated by Django 4.1.2 on 2023-03-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_strains_vf_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='strains',
            name='amr_summary',
            field=models.JSONField(null=True),
        ),
    ]
