# Generated by Django 4.1.2 on 2023-03-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_strains_amr_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='growth_type',
            field=models.CharField(db_index=True, default=None, max_length=5),
        ),
    ]
