# Generated by Django 4.1.2 on 2023-03-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_species_growth_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amr_genes',
            old_name='count_by_strains',
            new_name='number_of_strains',
        ),
    ]
