# Generated by Django 4.1.2 on 2023-03-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_amr_genes_number_of_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vf_genes',
            old_name='count_by_strains',
            new_name='number_of_strains',
        ),
    ]
