# Generated by Django 4.1.2 on 2023-03-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_vf_genes_number_of_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPtree',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('graph', models.JSONField(null=True)),
            ],
        ),
    ]
