# Generated by Django 4.1.2 on 2023-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_gptree'),
    ]

    operations = [
        migrations.AddField(
            model_name='strains',
            name='DST_test',
            field=models.BooleanField(default=False),
        ),
    ]
