# Generated by Django 4.1.2 on 2023-03-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_strains_dst_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='strains',
            name='representative',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
