# Generated by Django 4.1.2 on 2023-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_strains_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='grapetree_graph_path',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='rs_graph_path',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='vf_graph_path',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
