# Generated by Django 4.1.2 on 2023-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_rename_l50_contig_strains_l50_contigs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strains',
            name='checkm_completeness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='strains',
            name='checkm_contamination',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='strains',
            name='coding_density',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='strains',
            name='ssu_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='strains',
            name='trna_count',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
