# Generated by Django 4.1.2 on 2023-05-13 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_strains_checkm_completeness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DST',
            fields=[
                ('strain', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.strains')),
                ('Amikacin', models.JSONField(null=True)),
                ('Amikacin_D3', models.JSONField(null=True)),
                ('Amikacin_D5', models.JSONField(null=True)),
                ('Amikacin_D11', models.JSONField(null=True)),
                ('Amikacin_D14', models.JSONField(null=True)),
                ('Arginine', models.JSONField(null=True)),
                ('Azithromycin', models.JSONField(null=True)),
                ('Azithromycin_D3', models.JSONField(null=True)),
                ('Bactrim', models.JSONField(null=True)),
                ('Bedaquiline', models.JSONField(null=True)),
                ('Capreomycin', models.JSONField(null=True)),
                ('Cefoxitin', models.JSONField(null=True)),
                ('Cefoxitin_D3', models.JSONField(null=True)),
                ('Cefoxitin_D5', models.JSONField(null=True)),
                ('Cefoxitin_D11', models.JSONField(null=True)),
                ('Cefoxitin_D14', models.JSONField(null=True)),
                ('Chloramphenicol', models.JSONField(null=True)),
                ('Ciprofloxacin', models.JSONField(null=True)),
                ('Clarithromycin', models.JSONField(null=True)),
                ('Clarithromycin_D3', models.JSONField(null=True)),
                ('Clarithromycin_D4', models.JSONField(null=True)),
                ('Clarithromycin_D5', models.JSONField(null=True)),
                ('Clarithromycin_D11', models.JSONField(null=True)),
                ('Clarithromycin_D14', models.JSONField(null=True)),
                ('Clofazimine', models.JSONField(null=True)),
                ('Clofazimine_D3', models.JSONField(null=True)),
                ('Clofazimine_D5', models.JSONField(null=True)),
                ('Clofazimine_D11', models.JSONField(null=True)),
                ('D_cycloserine', models.JSONField(null=True)),
                ('Doxycycline', models.JSONField(null=True)),
                ('Erythromycin', models.JSONField(null=True)),
                ('Ethambutol', models.JSONField(null=True)),
                ('Ethionamide', models.JSONField(null=True)),
                ('Faropenem', models.JSONField(null=True)),
                ('Imipenem', models.JSONField(null=True)),
                ('Isoniazid', models.JSONField(null=True)),
                ('Levofloxacin', models.JSONField(null=True)),
                ('Linezolid', models.JSONField(null=True)),
                ('Linezolid_D3', models.JSONField(null=True)),
                ('Linezolid_D5', models.JSONField(null=True)),
                ('Linezolid_D11', models.JSONField(null=True)),
                ('Linezolid_D14', models.JSONField(null=True)),
                ('Meropenem', models.JSONField(null=True)),
                ('Minocycline', models.JSONField(null=True)),
                ('Moxifloxacin', models.JSONField(null=True)),
                ('Ofloxacin', models.JSONField(null=True)),
                ('Phleomycin', models.JSONField(null=True)),
                ('Rifabutin', models.JSONField(null=True)),
                ('Rifampicin', models.JSONField(null=True)),
                ('Rifamycin_SV', models.JSONField(null=True)),
                ('Streptomycin', models.JSONField(null=True)),
                ('Tetracycline', models.JSONField(null=True)),
                ('Thiocarbohydrazide', models.JSONField(null=True)),
                ('Thioridazine', models.JSONField(null=True)),
                ('Tigecycline', models.JSONField(null=True)),
                ('Tobramycin', models.JSONField(null=True)),
                ('Trimethoprim', models.JSONField(null=True)),
            ],
        ),
    ]
