# Generated by Django 4.1.2 on 2023-05-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_strains_subspecies_strains_subspecies_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amr_genes',
            name='definition',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
