# Generated by Django 4.1.2 on 2023-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_amr_genes_msa_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='vf_genes',
            name='msa_file_path',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
