# Generated by Django 4.1.2 on 2023-06-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_dst_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download_files',
            fields=[
                ('species', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('pan_genome_fasta', models.CharField(blank=True, default=None, max_length=100)),
                ('core_fastafasta', models.CharField(blank=True, default=None, max_length=100)),
                ('dispensable_fastafasta', models.CharField(blank=True, default=None, max_length=100)),
                ('unique_fasta', models.CharField(blank=True, default=None, max_length=100)),
                ('VF_csv', models.CharField(blank=True, default=None, max_length=100)),
                ('AMR_csv', models.CharField(blank=True, default=None, max_length=100)),
                ('MLST_csv', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
    ]
