# Generated by Django 4.1.2 on 2023-06-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_rename_core_fastafasta_download_files_core_fasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_files',
            name='taxid',
            field=models.CharField(db_index=True, default=None, max_length=55, unique=True),
        ),
    ]
