# Generated by Django 4.1.2 on 2023-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_download_files_taxid'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_files',
            name='strains_count',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
