# Generated by Django 4.1.2 on 2023-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_download_files_strains_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='growth_type',
            field=models.CharField(db_index=True, default=None, max_length=10),
        ),
    ]
